apiVersion: v1
kind: Service
metadata:
  name: multicast-api-0
spec:
  selector:
    app: multicast-api
    process: "0"
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: multicast-api-1
spec:
  selector:
    app: multicast-api
    process: "1"
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: multicast-api-2
spec:
  selector:
    app: multicast-api
    process: "2"
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
