apiVersion: v1
kind: Service
metadata:
  name: multicast-api-0
  namespace: default
spec:
  type: NodePort
  selector:
    app: multicast-api
    statefulset.kubernetes.io/pod-name: multicast-api-0
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: multicast-api-1
  namespace: default
spec:
  type: NodePort
  selector:
    app: multicast-api
    statefulset.kubernetes.io/pod-name: multicast-api-1
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: multicast-api-2
  namespace: default
spec:
  type: NodePort
  selector:
    app: multicast-api
    statefulset.kubernetes.io/pod-name: multicast-api-2
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
    name: http
